[package]
name = "onair"
version = "0.1.0"
authors = ["YushiOMOTE <yushiomote@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.3"
env_logger = "0.9.0"
serde = "1.0.136"
